INSERT INTO yin_data.t_objects
	(
	obid, 
	ok2id, 
	geox, 
	geoy, 
	bgid, 
	strasse, 
	hausnr, 
	plz, 
	ort, 
	wohnflaeche, 
	zimmeranzahl, 
	baujahr, 
	courtage, 
	kaufpreis, 
	kaufvermietet, 
	nebenkosten, 
	zusatzkosten, 
	ueberschrift, 
	url, 
	edatum, 
	parkflaechenzahl, 
	parkflaechenpreis, 
	etage, 
	mieteinnahmenpromonat, 
	heizkosten, 
	letzte_modernisierung, 
	keller, 
	barrierefrei, 
	denkmalobjekt) 
SELECT
	obid, ok2id, geox, geoy, bgid, strasse, hausnr, plz, ort,
	replace( wohnflaeche, ',', '.') :: double precision,
	replace( zimmeranzahl, ',', '.') :: double precision, 
	baujahr, 
	courtage, 
	replace( kaufpreis, ',', '.') :: double precision, 
	CASE WHEN kaufvermietet IS NULL THEN NULL ELSE CASE WHEN kaufvermietet ='Y' THEN TRUE ELSE FALSE END END, 
	replace( nebenkosten, ',', '.') :: double precision, 
	replace( zusatzkosten, ',', '.') :: double precision, 
	ueberschrift, 
	url, 
	edatum, 
	parkflaechenzahl, 
	replace( parkflaechenpreis, ',', '.') :: double precision, 
	etage, 
	replace( mieteinnahmenpromonat, ',', '.') :: double precision, 
	replace( heizkosten, ',', '.') :: double precision, 
	letzte_modernisierung, 
	CASE WHEN keller IS NULL THEN NULL ELSE CASE WHEN keller ='Y' THEN TRUE ELSE FALSE END END, 
	CASE WHEN barrierefrei IS NULL THEN NULL ELSE CASE WHEN barrierefrei ='Y' THEN TRUE ELSE FALSE END END, 
	CASE WHEN denkmalobjekt IS NULL THEN NULL ELSE CASE WHEN denkmalobjekt ='Y' THEN TRUE ELSE FALSE END END 

FROM is24_data.objects;

