DROP TABLE IF EXISTS is24_data.objects;

CREATE TABLE is24_data.objects
(
  GKZ VARCHAR(30) 
, OBID bigint NOT NULL 
, SCOUTID VARCHAR(15) 
, SOID bigint
, OQID bigint NOT NULL 
, OK1ID integer
, OK2ID integer 
, VTCODE CHAR(1) 
, STCODE_STANDORT CHAR(1) NOT NULL 
, STCODE_IS CHAR(1) NOT NULL 
, NTCODE CHAR(1) 
, SPCODE CHAR(2) NOT NULL 
, WACODE CHAR(3) NOT NULL 
, ZICODE CHAR(1) NOT NULL 
, ABGELEITET_VON bigint 
, ANBIETEROBJEKTKATEGORIE VARCHAR(50) 
, ADRESSEZEIGEN CHAR(1) NOT NULL 
, QUELLEREFNUM VARCHAR(40) 
, ANBIETERREFNUM VARCHAR(50) NOT NULL 
, GEOX bigint 
, GEOY bigint 
, KOID integer 
, LAID integer 
, BLID integer 
, SKID integer 
, BGID integer 
, STRASSE VARCHAR(100) 
, HAUSNR VARCHAR(30) 
, PLZ VARCHAR(20) 
, ORT VARCHAR(50) 
, WOHNFLAECHE text 
, ZIMMERANZAHL text 
, BAUJAHR integer 
, COURTAGE VARCHAR(100) 
, MIETEKALT text 
, MIETEWARM text 
, MIETEKAUTION VARCHAR(50) 
, KAUFPREIS text 
, KAUFVERMIETET CHAR(1) 
, NEBENKOSTEN text 
, ZUSATZKOSTEN VARCHAR(50) 
, FREIAB VARCHAR(50) 
, VERKEHRSWERT text
, VERSTEIGERUNGSTERMIN DATE 
, UEBERSCHRIFT VARCHAR(100) 
, URL VARCHAR(300) 
, ENUTZER VARCHAR(40) NOT NULL 
, EDATUM DATE NOT NULL 
, GNUTZER VARCHAR(40) 
, GDATUM DATE 
, ODS_SEQ_DTUE DECIMAL NOT NULL 
, ODS_LOGID DECIMAL NOT NULL 
, ODS_TS DATE NOT NULL 
, ODS_G_SEQ_DTUE DECIMAL 
, ODS_G_LOGID DECIMAL 
, ODS_STCODE CHAR(1) 
, ODS_G_ODS_TS DATE 
, TEMP VARCHAR(50) 
, MIETEPROQM text
, BOBID bigint
, NUTZFLAECHE text
, HAUPTFLAECHE text
, NEBENFLAECHE text 
, PARKFLAECHENZAHL bigint
, PARKFLAECHENPREIS text
, FUSSWEG_OEPNV bigint
, FAHRZEIT_HBHF bigint
, FAHRZEIT_BAB integer 
, FAHRZEIT_AIRPORT integer 
, ETAGE VARCHAR(50) 
, OZID bigint
, ITTYP bigint NOT NULL 
, ANREFNUM_IS bigint
, MIETEINNAHMENPROMONAT text
, DEAKTIVIERUNGSDATUM DATE 
, AENDERUNGSDATUM DATE 
, ANID bigint NOT NULL 
, HAUSNRVON bigint
, HAUSNRBIS bigint
, HEIZKOSTEN text
, HP_AKTIV CHAR(1) NOT NULL 
, HEIZKOSTEN_IN_WM_ENTHALTEN CHAR(1) 
, GRUPPENSTATUS bigint
, API_SUCHFELD1 VARCHAR(16) 
, API_SUCHFELD2 VARCHAR(16) 
, API_SUCHFELD3 VARCHAR(16) 
, GQID DECIMAL(6, 0) 
, APWID integer 
, ERSTE_AKTIVIERUNG DATE 
, LETZTE_MODERNISIERUNG integer
, HAID bigint
, AQID DECIMAL 
, EATID DECIMAL 
, BPAID DECIMAL 
, WGID DECIMAL 
, EV_KENNWERT text 
, EV_WWENTHALTEN CHAR(1) 
, GEM_GESCHAEFT_MOEGLICH CHAR(1) 
, PROVISION_ANZEIGEN CHAR(1) 
, KELLER CHAR(1) 
, BARRIEREFREI CHAR(1) 
, DENKMALOBJEKT CHAR(1) 
, QUARTID bigint
, ARCHIVIERUNGSDATUM DATE 
, GRUNDFLAECHE text 
, ADID_KONTAKT bigint
, MIETEPROQM_BERECHNET text DEFAULT 0 
, MIETEKALT_BERECHNET text DEFAULT 0 
, IMMOBILIENPROJEKT_ID bigint
, DUBLETTE_VON_OBID bigint
, VERSION bigint NOT NULL 
, SYSTEM_ID bigint
, KONTAKTFORMULAR_KONFIG_ID bigint
, WT_ENERGIE_EFFIZENZ_KLASSE_ID bigint
, EV_ERSTELLUNGS_TYP CHAR(1) 
, EV_STROMVERBRAUCHSKENNWERT text 
, EV_HEIZENERGIEVERBRAUCHSKENNW text 
, EV_ENDENERGIEVERBRAUCH_STROM text 
, EV_ENDENERGIEVERBRAUCH_WAERME text 
, EV_ENDENERGIEBEDARF_STROM text 
, EV_ENDENERGIEBEDARF_WAERME text 
, EV_ENDENERGIEVERERBRAUCH text 
, EV_BAUJAHR_NICHT_BEKANNT CHAR(1) 
, EV_LAYER_VERBERGEN CHAR(1) 
, EV_ENERGIEAUSWEIS integer
, ADRESSE_MEHRDEUTIG CHAR(1)
);
