CREATE TABLE t_objects
(
    obid BIGINT NOT NULL,
    ok2id INT,
    geox BIGINT,
    geoy BIGINT,
    bgid INT,
    strasse VARCHAR(100),
    hausnr VARCHAR(30),
    plz VARCHAR(20),
    ort VARCHAR(50),
    wohnflaeche DOUBLE PRECISION,
    zimmeranzahl DOUBLE PRECISION,
    baujahr INT,
    courtage VARCHAR(100),
    kaufpreis DOUBLE PRECISION,
    kaufvermietet BOOL,
    nebenkosten DOUBLE PRECISION,
    zusatzkosten DOUBLE PRECISION,
    ueberschrift VARCHAR(100),
    url VARCHAR(300),
    edatum DATE NOT NULL,
    parkflaechenzahl BIGINT,
    parkflaechenpreis DOUBLE PRECISION,
    etage VARCHAR(50),
    mieteinnahmenpromonat DOUBLE PRECISION,
    heizkosten DOUBLE PRECISION,
    letzte_modernisierung INT,
    keller BOOL,
    barrierefrei BOOL,
    denkmalobjekt BOOL
);
